#!/bin/sh

USER=tiddlyweb
NODE_PATH=/usr/local/lib/node
DAEMON=/home/cdent/src/tiddlyspacesockets/server/twsock.js
NODE_BIN=/usr/local/bin/node

set -e

echo "(re-)starting twsock.js" | logger -p syslog.info -t twsock
sudo -u $USER $NODE_BIN $DAEMON &
echo $! > /var/run/twsock.pid
