#!/bin/sh

USER=tiddlyweb
NODE_PATH=/usr/local/lib/node
DAEMON=twsock

set -e

echo "(re-)starting twsock.js" | logger -p syslog.info -t twsock
sudo -u $USER $DAEMON | logger -p syslog.info -t twsock
